name = "Originsserver"
author = "Origins Server Pack (placeholder name)"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "07e51ac79e5dc0c3826b98919fa679eb812d0f6649cc67646af368b3778ae45a"

[versions]
fabric = "0.16.3"
minecraft = "1.20.1"
