name = "Originsserver"
author = "Origins Server Pack (placeholder name)"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "181c72fe7c6426a287164762520452cce5d632b23468a125458922765bbcdcbf"

[versions]
fabric = "0.16.3"
minecraft = "1.20.1"
