name = "Originsserver"
author = "Origins Server Pack (placeholder name)"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "1eb73f4086758aa245344fa73abc1967131e982a906bfb314fff5c28b66a9902"

[versions]
fabric = "0.16.3"
minecraft = "1.20.1"
