name = "Originsserver"
author = "Origins Server Pack (placeholder name)"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "c437c35412429296cd4d7b5ad37d4a0057283167358c04d0f21b09bf3c884b2b"

[versions]
fabric = "0.16.3"
minecraft = "1.20.1"
