name = "Originsserver"
author = "Origins Server Pack (placeholder name)"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "79d1066c3eb4e64624a7e5cace8f2907b2d3d94e26e133ece376d996fc28e531"

[versions]
fabric = "0.16.3"
minecraft = "1.20.1"
