name = "Originsserver"
author = "Origins Server Pack (placeholder name)"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "9691c238869b150f2924c57a9662592da70951476d3c8c0b70292142e0320285"

[versions]
fabric = "0.16.3"
minecraft = "1.20.1"
